name: eais2
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.14
  - aom=3.9.1
  - attr=2.5.1
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-blosc2=2.15.2
  - ca-certificates=2025.1.31
  - cairo=1.18.4
  - charls=2.4.2
  - contourpy=1.3.2
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dav1d=1.2.1
  - dbus=1.13.6
  - double-conversion=3.3.1
  - expat=2.7.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.57.0
  - freetype=2.13.3
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - giflib=5.2.2
  - glib=2.84.1
  - glib-tools=2.84.1
  - graphite2=1.3.13
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - harfbuzz=11.1.0
  - hj-reachability=0.7.0
  - icu=75.1
  - imagecodecs=2024.12.30
  - imageio=2.37.0
  - importlib-metadata=8.6.1
  - joblib=1.4.2
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libaec=1.1.3
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libavif16=1.2.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.75
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.3
  - libclang13=20.1.3
  - libcups=2.3.3
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.6
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.84.1
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgpg-error=1.54
  - libhwy=1.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.0.0
  - libjxl=0.11.1
  - liblapack=3.9.0
  - libllvm20=20.1.3
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.29
  - libopengl=1.7.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.4
  - libsndfile=1.2.2
  - libsqlite=3.49.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=257.4
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.8.1
  - libxml2=2.13.7
  - libxslt=1.1.39
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - lz4-c=1.10.0
  - matplotlib=3.10.1
  - matplotlib-base=3.10.1
  - mpg123=1.32.9
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - ncurses=6.5
  - nspr=4.36
  - nss=3.110
  - numpy=2.2.4
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.5.0
  - packaging=25.0
  - pcre2=10.44
  - pillow=11.1.0
  - pip=25.0.1
  - pixman=0.44.2
  - pthread-stubs=0.4
  - pulseaudio-client=17.0
  - pyparsing=3.2.3
  - pyside2=5.15.15
  - pyside6=6.9.0
  - python=3.10.17
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pywavelets=1.8.0
  - qhull=2020.2
  - qt-main=5.15.15
  - qt6-main=6.9.0
  - rav1e=0.6.6
  - readline=8.2
  - scikit-fmm=2025.1.29
  - scikit-image=0.25.2
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - setuptools=78.1.0
  - six=1.17.0
  - snappy=1.2.1
  - svt-av1=3.0.2
  - threadpoolctl=3.6.0
  - tifffile=2025.3.30
  - tk=8.6.13
  - tornado=6.4.2
  - tzdata=2025b
  - unicodedata2=16.0.0
  - wayland=1.23.1
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - zfp=1.0.1
  - zipp=3.21.0
  - zlib-ng=2.2.4
  - zstd=1.5.7
  - pip:
      - absl-py==2.2.2
      - chex==0.1.89
      - dataclasses-json==0.6.7
      - etils==1.12.2
      - flax==0.10.5
      - fsspec==2025.3.2
      - gymnasium==0.28.1
      - humanize==4.12.2
      - jax==0.6.0
      - jaxlib==0.6.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.26.1
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - msgpack==1.1.0
      - mypy-extensions==1.0.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - nptyping==1.4.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - opt-einsum==3.4.0
      - optax==0.2.4
      - orbax-checkpoint==0.11.12
      - pettingzoo==1.24.3
      - protobuf==6.30.2
      - pybullet==3.2.5
      - rich==14.0.0
      - simplejson==3.20.1
      - sympy==1.13.1
      - tensorstore==0.1.73
      - toolz==1.0.0
      - torch==2.6.0+cu126
      - torchvision==0.21.0+cu126
      - treescope==0.1.9
      - triton==3.2.0
      - typing-inspect==0.9.0
      - typish==1.9.3
      - yamldataclassconfig==1.5.0
